CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA security;
CREATE SCHEMA core;
CREATE SCHEMA catalog;
CREATE SCHEMA training;
CREATE SCHEMA finance;
CREATE SCHEMA notification;
CREATE SCHEMA skill;
CREATE SCHEMA infrastructure;

CREATE TABLE security.users (
    user_id UUID PRIMARY KEY,
    phone_number VARCHAR(20) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    user_status VARCHAR(20) NOT NULL,
    authorization_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    last_login_at TIMESTAMP,
    CONSTRAINT ck_user_status CHECK (user_status IN ('PENDING', 'ACTIVE', 'LOCKED', 'DISABLED', 'BANNED'))
);

CREATE TABLE security.role (
    role_id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    permission_version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE security.permission (
    permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    model VARCHAR(50) NOT NULL,
    action VARCHAR(30) NOT NULL,
    description VARCHAR(255) NOT NULL,
    CONSTRAINT ck_permission_action CHECK (action IN ('CREATE', 'UPDATE', 'READ', 'DELETE', 'APPROVE'))
);

CREATE TABLE security.user_role (
    user_id UUID NOT NULL REFERENCES security.users(user_id),
    role_id VARCHAR(50) NOT NULL REFERENCES security.role(role_id),
    PRIMARY KEY (user_id, role_id)
);
CREATE INDEX idx_user_role_role ON security.user_role(role_id);

CREATE TABLE security.role_permission (
    role_id VARCHAR(50) NOT NULL REFERENCES security.role(role_id),
    permission_id INTEGER NOT NULL REFERENCES security.permission(permission_id),
    PRIMARY KEY (role_id, permission_id)
);
CREATE INDEX idx_role_permission_permission ON security.role_permission(permission_id);

CREATE TABLE core.person (
    person_id UUID PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    gender BOOLEAN,
    birth_date DATE,
    email VARCHAR(100),
    national_code VARCHAR(50) UNIQUE,
    face_embedding vector(512),
    face_image_path VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    person_code VARCHAR(50) UNIQUE,
    belt VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    start_date DATE,
    CONSTRAINT ck_person_belt CHECK (belt IN (
        'C10', 'C9', 'C8', 'C7', 'C6', 'C5', 'C4', 'C3', 'C2', 'C1',
        'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10'
    )),
    CONSTRAINT ck_person_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE TABLE core.user_person (
    user_person_id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES security.users(user_id),
    person_id UUID NOT NULL REFERENCES core.person(person_id),
    relationship_type VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_person_relationship UNIQUE (user_id, person_id, relationship_type),
    CONSTRAINT ck_user_person_relationship CHECK (relationship_type IN ('OWNER', 'GUARDIAN', 'MANAGER'))
);
CREATE INDEX idx_user_person_person ON core.user_person(person_id);

CREATE TABLE security.auth_session (
    auth_session_id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES security.users(user_id),
    refresh_token_hash VARCHAR(64) NOT NULL UNIQUE,
    device_info VARCHAR(255),
    platform VARCHAR(20),
    fcm_token VARCHAR(500),
    active_user_person_id UUID REFERENCES core.user_person(user_person_id),
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_auth_session_user ON security.auth_session(user_id);

CREATE TABLE core.branch (
    branch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    hotline VARCHAR(20),
    opened_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_branch_status CHECK (status IN ('OPERATING', 'CLOSED', 'MAINTENANCE'))
);

CREATE TABLE catalog.class_schedule (
    schedule_id UUID PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES core.branch(branch_id),
    weekday VARCHAR(20) NOT NULL,
    level VARCHAR(20) NOT NULL,
    location VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    CONSTRAINT ck_schedule_time CHECK (end_time > start_time),
    CONSTRAINT ck_schedule_weekday CHECK (weekday IN (
        'SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'
    )),
    CONSTRAINT ck_schedule_level CHECK (level IN ('BASIC', 'ADVANCED', 'EXPERT')),
    CONSTRAINT ck_schedule_location CHECK (location IN ('INDOOR', 'OUTDOOR', 'ONLINE')),
    CONSTRAINT ck_schedule_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE catalog.course (
    course_id UUID PRIMARY KEY,
    schedule_id UUID NOT NULL REFERENCES catalog.class_schedule(schedule_id),
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_course_status CHECK (status IN ('OPEN', 'ACTIVE', 'CLOSED', 'CANCELLED'))
);

CREATE TABLE catalog.course_price (
    course_price_id UUID PRIMARY KEY,
    course_id UUID NOT NULL REFERENCES catalog.course(course_id),
    duration_months INTEGER NOT NULL CHECK (duration_months > 0),
    session_count INTEGER NOT NULL CHECK (session_count > 0),
    base_price NUMERIC(19,0) NOT NULL CHECK (base_price >= 0),
    final_price NUMERIC(19,0) NOT NULL CHECK (final_price >= 0),
    status VARCHAR(20) NOT NULL,
    CONSTRAINT ck_course_price_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE finance.wallet (
    wallet_id UUID PRIMARY KEY,
    person_id UUID NOT NULL UNIQUE REFERENCES core.person(person_id),
    balance NUMERIC(19,0) NOT NULL DEFAULT 0 CHECK (balance >= 0),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_wallet_status CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED'))
);

CREATE TABLE finance.wallet_transaction (
    wallet_transaction_id UUID PRIMARY KEY,
    wallet_id UUID NOT NULL REFERENCES finance.wallet(wallet_id),
    type VARCHAR(30) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    amount NUMERIC(19,0) NOT NULL CHECK (amount > 0),
    balance_before NUMERIC(19,0) NOT NULL CHECK (balance_before >= 0),
    balance_after NUMERIC(19,0) NOT NULL CHECK (balance_after >= 0),
    external_reference VARCHAR(150) NOT NULL,
    created_by_user_id UUID NOT NULL REFERENCES security.users(user_id),
    approved_by_user_id UUID REFERENCES security.users(user_id),
    approved_at TIMESTAMP,
    note VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT ck_wallet_tx_type CHECK (type IN (
        'TOP_UP', 'COURSE_PURCHASE', 'SUPPLY_PURCHASE', 'REFUND', 'MANUAL_ADJUSTMENT'
    )),
    CONSTRAINT ck_wallet_tx_direction CHECK (direction IN ('CREDIT', 'DEBIT')),
    CONSTRAINT ck_wallet_tx_status CHECK (status IN ('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED')),
    CONSTRAINT uk_wallet_tx_type_reference UNIQUE (type, external_reference)
);
CREATE INDEX idx_wallet_tx_wallet_created ON finance.wallet_transaction(wallet_id, created_at DESC);

CREATE TABLE finance.course_purchase (
    course_purchase_id UUID PRIMARY KEY,
    student_person_id UUID NOT NULL REFERENCES core.person(person_id),
    course_price_id UUID NOT NULL REFERENCES catalog.course_price(course_price_id),
    debit_transaction_id UUID NOT NULL UNIQUE REFERENCES finance.wallet_transaction(wallet_transaction_id)
);
CREATE INDEX idx_course_purchase_price ON finance.course_purchase(course_price_id);

CREATE TABLE training.student_enrollment (
    student_enrollment_id UUID PRIMARY KEY,
    student_person_id UUID NOT NULL REFERENCES core.person(person_id),
    course_purchase_id UUID NOT NULL UNIQUE REFERENCES finance.course_purchase(course_purchase_id),
    class_schedule_id UUID NOT NULL REFERENCES catalog.class_schedule(schedule_id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_enrollment_status CHECK (status IN (
        'PENDING_START', 'ACTIVE', 'COMPLETED', 'EXPIRED', 'CANCELLED'
    ))
);
CREATE INDEX idx_enrollment_schedule ON training.student_enrollment(class_schedule_id);

CREATE TABLE training.class_session (
    class_session_id UUID PRIMARY KEY,
    course_id UUID NOT NULL REFERENCES catalog.course(course_id),
    session_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    is_attendance_closed BOOLEAN NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    note VARCHAR(500),
    CONSTRAINT ck_class_session_status CHECK (status IN (
        'SCHEDULED', 'ACTIVE', 'COMPLETED', 'TERMINATED', 'CANCELLED', 'POSTPONED'
    ))
);

CREATE TABLE training.student_attendance (
    student_attendance_id UUID PRIMARY KEY,
    class_session_id UUID NOT NULL REFERENCES training.class_session(class_session_id),
    student_enrollment_id UUID NOT NULL REFERENCES training.student_enrollment(student_enrollment_id),
    check_in_time TIMESTAMP,
    attendance_status VARCHAR(20) NOT NULL,
    evaluation_status VARCHAR(20),
    evaluated_by_coach_id UUID REFERENCES core.person(person_id),
    note VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_attendance_session_enrollment UNIQUE (class_session_id, student_enrollment_id),
    CONSTRAINT ck_attendance_status CHECK (attendance_status IN (
        'PRESENT', 'ABSENT', 'EXCUSED', 'MAKEUP', 'LATE'
    )),
    CONSTRAINT ck_evaluation_status CHECK (
        evaluation_status IS NULL OR evaluation_status IN ('PENDING', 'GOOD', 'AVERAGE', 'WEAK')
    )
);
CREATE INDEX idx_attendance_enrollment ON training.student_attendance(student_enrollment_id);

CREATE TABLE training.coach_assignment (
    coach_assignment_id UUID PRIMARY KEY,
    coach_person_id UUID NOT NULL REFERENCES core.person(person_id),
    course_id UUID NOT NULL REFERENCES catalog.course(course_id),
    assigned_date DATE NOT NULL,
    end_date DATE,
    coach_assignment_status VARCHAR(20) NOT NULL,
    note VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_coach_assignment_status CHECK (coach_assignment_status IN (
        'PENDING', 'ACTIVE', 'SUSPENDED', 'ENDED', 'CANCELLED'
    ))
);
CREATE INDEX idx_coach_assignment_course ON training.coach_assignment(course_id);

CREATE TABLE training.coach_timesheet (
    coach_timesheet_id UUID PRIMARY KEY,
    coach_assignment_id UUID NOT NULL REFERENCES training.coach_assignment(coach_assignment_id),
    class_session_id UUID NOT NULL REFERENCES training.class_session(class_session_id),
    check_in_time TIME,
    check_out_time TIME,
    note VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_timesheet_assignment_session UNIQUE (coach_assignment_id, class_session_id)
);

CREATE TABLE notification.notification (
    notification_id UUID PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    body VARCHAR(1000) NOT NULL,
    notification_type VARCHAR(40) NOT NULL,
    reference_type VARCHAR(100),
    reference_id VARCHAR(100),
    payload TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_notification_type CHECK (notification_type IN (
        'SYSTEM', 'ATTENDANCE', 'TUITION', 'CLASS_SCHEDULE', 'COACH_TIMESHEET',
        'ANNOUNCEMENT', 'CLASS_SESSION_REPORT'
    ))
);

CREATE TABLE notification.notification_recipient (
    notification_recipient_id UUID PRIMARY KEY,
    notification_id UUID NOT NULL REFERENCES notification.notification(notification_id),
    recipient_user_id UUID NOT NULL REFERENCES security.users(user_id),
    read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMP,
    delivered_at TIMESTAMP,
    notification_recipient_status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_notification_recipient UNIQUE (notification_id, recipient_user_id),
    CONSTRAINT ck_notification_recipient_status CHECK (notification_recipient_status IN (
        'PENDING', 'SENT', 'ARCHIVED', 'FAILED'
    ))
);
CREATE INDEX idx_notification_recipient_user ON notification.notification_recipient(recipient_user_id);

CREATE TABLE skill.fitness (
    fitness_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_level VARCHAR(20) NOT NULL,
    amount INTEGER NOT NULL CHECK (amount > 0),
    duration INTEGER NOT NULL CHECK (duration > 0),
    CONSTRAINT ck_fitness_schedule_level CHECK (schedule_level IN ('BASIC', 'ADVANCED', 'EXPERT'))
);

CREATE TABLE skill.fitness_record (
    fitness_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_date DATE NOT NULL,
    student_person_id UUID NOT NULL REFERENCES core.person(person_id),
    duration INTEGER NOT NULL CHECK (duration > 0),
    fitness_id BIGINT NOT NULL REFERENCES skill.fitness(fitness_id),
    recorded_by_coach_id UUID NOT NULL REFERENCES core.person(person_id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
